import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'
import { Navigation } from '@/src/components/Navigation'
import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-8 pb-8 w-full`}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        <Navigation />
        {children}
        </ThemeProvider>
        </body>
    </html>
  )
}
